### ISSUE TITLE
支持实时语音识别

### ISSUE THREAD

**Issue by Yikai-Liao** [pofice/linux-voice-input-method#1]
我看了一下FunASR的文档，是有支持实时语音检测的版本的。但是考虑到目前是模拟cltr v进行输入，是不是支持实时识别(类似手机语音输入)比较困难。

**Comment by pofice** [comment]
这个版本已经很快了，实测是要快于讯飞的手机语音输入的

**Comment by Yikai-Liao** [comment]
快确实是快，就是松手才出字有点不习惯。不过还好，比whisper可用性高多了
